/* Auto-generated by genmsg_cpp for file /home/venkat/ros_workspace/uavros/uav_msgs/msg/ControllerCommand.msg */
#ifndef UAV_MSGS_MESSAGE_CONTROLLERCOMMAND_H
#define UAV_MSGS_MESSAGE_CONTROLLERCOMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace uav_msgs
{
template <class ContainerAllocator>
struct ControllerCommand_ {
  typedef ControllerCommand_<ContainerAllocator> Type;

  ControllerCommand_()
  : header()
  , thrust(0)
  , roll(0)
  , pitch(0)
  , yaw(0)
  {
  }

  ControllerCommand_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , thrust(0)
  , roll(0)
  , pitch(0)
  , yaw(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _thrust_type;
  uint8_t thrust;

  typedef uint8_t _roll_type;
  uint8_t roll;

  typedef uint8_t _pitch_type;
  uint8_t pitch;

  typedef uint8_t _yaw_type;
  uint8_t yaw;


private:
  static const char* __s_getDataType_() { return "uav_msgs/ControllerCommand"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "09321cf2ffc9c3330500a4bf05bbdd35"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
uint8 thrust\n\
uint8 roll\n\
uint8 pitch\n\
uint8 yaw\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, thrust);
    ros::serialization::serialize(stream, roll);
    ros::serialization::serialize(stream, pitch);
    ros::serialization::serialize(stream, yaw);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, thrust);
    ros::serialization::deserialize(stream, roll);
    ros::serialization::deserialize(stream, pitch);
    ros::serialization::deserialize(stream, yaw);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(thrust);
    size += ros::serialization::serializationLength(roll);
    size += ros::serialization::serializationLength(pitch);
    size += ros::serialization::serializationLength(yaw);
    return size;
  }

  typedef boost::shared_ptr< ::uav_msgs::ControllerCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::ControllerCommand_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ControllerCommand
typedef  ::uav_msgs::ControllerCommand_<std::allocator<void> > ControllerCommand;

typedef boost::shared_ptr< ::uav_msgs::ControllerCommand> ControllerCommandPtr;
typedef boost::shared_ptr< ::uav_msgs::ControllerCommand const> ControllerCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::uav_msgs::ControllerCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::uav_msgs::ControllerCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace uav_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::uav_msgs::ControllerCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::uav_msgs::ControllerCommand_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::ControllerCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "09321cf2ffc9c3330500a4bf05bbdd35";
  }

  static const char* value(const  ::uav_msgs::ControllerCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x09321cf2ffc9c333ULL;
  static const uint64_t static_value2 = 0x0500a4bf05bbdd35ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::ControllerCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uav_msgs/ControllerCommand";
  }

  static const char* value(const  ::uav_msgs::ControllerCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::ControllerCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint8 thrust\n\
uint8 roll\n\
uint8 pitch\n\
uint8 yaw\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::uav_msgs::ControllerCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::uav_msgs::ControllerCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::uav_msgs::ControllerCommand_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::uav_msgs::ControllerCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.thrust);
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ControllerCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::ControllerCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::uav_msgs::ControllerCommand_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "thrust: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.thrust);
    s << indent << "roll: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_CONTROLLERCOMMAND_H

