//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the uav_local_planner package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __uav_local_planner__TUTORIALSCONFIG_H__
#define __uav_local_planner__TUTORIALSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace uav_local_planner
{
  class TutorialsConfigStatics;
  
  class TutorialsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(TutorialsConfig &config, const TutorialsConfig &max, const TutorialsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const TutorialsConfig &config1, const TutorialsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, TutorialsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const TutorialsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, TutorialsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const TutorialsConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T TutorialsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (TutorialsConfig::* field);

      virtual void clamp(TutorialsConfig &config, const TutorialsConfig &max, const TutorialsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const TutorialsConfig &config1, const TutorialsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, TutorialsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const TutorialsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, TutorialsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const TutorialsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 9 "../cfg/uav_local_planner.cfg"
      double RPkp;
//#line 10 "../cfg/uav_local_planner.cfg"
      double RPkd;
//#line 11 "../cfg/uav_local_planner.cfg"
      double RPki;
//#line 13 "../cfg/uav_local_planner.cfg"
      double Ykp;
//#line 14 "../cfg/uav_local_planner.cfg"
      double Ykd;
//#line 15 "../cfg/uav_local_planner.cfg"
      double Yki;
//#line 17 "../cfg/uav_local_planner.cfg"
      double Tkp;
//#line 18 "../cfg/uav_local_planner.cfg"
      double Tkd;
//#line 19 "../cfg/uav_local_planner.cfg"
      double Tki;
//#line 21 "../cfg/uav_local_planner.cfg"
      double Posekp;
//#line 22 "../cfg/uav_local_planner.cfg"
      double Posekd;
//#line 23 "../cfg/uav_local_planner.cfg"
      double Poseki;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("TutorialsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const TutorialsConfig &__max__ = __getMax__();
      const TutorialsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const TutorialsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const TutorialsConfig &__getDefault__();
    static const TutorialsConfig &__getMax__();
    static const TutorialsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const TutorialsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void TutorialsConfig::ParamDescription<std::string>::clamp(TutorialsConfig &config, const TutorialsConfig &max, const TutorialsConfig &min) const
  {
    return;
  }

  class TutorialsConfigStatics
  {
    friend class TutorialsConfig;
    
    TutorialsConfigStatics()
    {
//#line 9 "../cfg/uav_local_planner.cfg"
      __min__.RPkp = 0.0;
//#line 9 "../cfg/uav_local_planner.cfg"
      __max__.RPkp = 100.0;
//#line 9 "../cfg/uav_local_planner.cfg"
      __default__.RPkp = 20.0;
//#line 9 "../cfg/uav_local_planner.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("RPkp", "double", 0, "Roll/Pitch Proportional Gain", "", &TutorialsConfig::RPkp)));
//#line 10 "../cfg/uav_local_planner.cfg"
      __min__.RPkd = 0.0;
//#line 10 "../cfg/uav_local_planner.cfg"
      __max__.RPkd = 100.0;
//#line 10 "../cfg/uav_local_planner.cfg"
      __default__.RPkd = 2.5;
//#line 10 "../cfg/uav_local_planner.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("RPkd", "double", 0, "Roll/Pitch Derivative Gain", "", &TutorialsConfig::RPkd)));
//#line 11 "../cfg/uav_local_planner.cfg"
      __min__.RPki = 0.0;
//#line 11 "../cfg/uav_local_planner.cfg"
      __max__.RPki = 100.0;
//#line 11 "../cfg/uav_local_planner.cfg"
      __default__.RPki = 0.03;
//#line 11 "../cfg/uav_local_planner.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("RPki", "double", 0, "Roll/Pitch Integral Gain", "", &TutorialsConfig::RPki)));
//#line 13 "../cfg/uav_local_planner.cfg"
      __min__.Ykp = 0.0;
//#line 13 "../cfg/uav_local_planner.cfg"
      __max__.Ykp = 100.0;
//#line 13 "../cfg/uav_local_planner.cfg"
      __default__.Ykp = 6.0;
//#line 13 "../cfg/uav_local_planner.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("Ykp", "double", 0, "Yaw Proportional Gain", "", &TutorialsConfig::Ykp)));
//#line 14 "../cfg/uav_local_planner.cfg"
      __min__.Ykd = 0.0;
//#line 14 "../cfg/uav_local_planner.cfg"
      __max__.Ykd = 100.0;
//#line 14 "../cfg/uav_local_planner.cfg"
      __default__.Ykd = 11.0;
//#line 14 "../cfg/uav_local_planner.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("Ykd", "double", 0, "Yaw Derivative Gain", "", &TutorialsConfig::Ykd)));
//#line 15 "../cfg/uav_local_planner.cfg"
      __min__.Yki = 0.0;
//#line 15 "../cfg/uav_local_planner.cfg"
      __max__.Yki = 100.0;
//#line 15 "../cfg/uav_local_planner.cfg"
      __default__.Yki = 0.0;
//#line 15 "../cfg/uav_local_planner.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("Yki", "double", 0, "Yaw Integral Gain", "", &TutorialsConfig::Yki)));
//#line 17 "../cfg/uav_local_planner.cfg"
      __min__.Tkp = 0.0;
//#line 17 "../cfg/uav_local_planner.cfg"
      __max__.Tkp = 100.0;
//#line 17 "../cfg/uav_local_planner.cfg"
      __default__.Tkp = 10.0;
//#line 17 "../cfg/uav_local_planner.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("Tkp", "double", 0, "Thrust Proportional Gain", "", &TutorialsConfig::Tkp)));
//#line 18 "../cfg/uav_local_planner.cfg"
      __min__.Tkd = 0.0;
//#line 18 "../cfg/uav_local_planner.cfg"
      __max__.Tkd = 100.0;
//#line 18 "../cfg/uav_local_planner.cfg"
      __default__.Tkd = 6.0;
//#line 18 "../cfg/uav_local_planner.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("Tkd", "double", 0, "Thrust Derivative  Gain", "", &TutorialsConfig::Tkd)));
//#line 19 "../cfg/uav_local_planner.cfg"
      __min__.Tki = 0.0;
//#line 19 "../cfg/uav_local_planner.cfg"
      __max__.Tki = 100.0;
//#line 19 "../cfg/uav_local_planner.cfg"
      __default__.Tki = 0.1;
//#line 19 "../cfg/uav_local_planner.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("Tki", "double", 0, "Thrust Integral Gain", "", &TutorialsConfig::Tki)));
//#line 21 "../cfg/uav_local_planner.cfg"
      __min__.Posekp = 0.0;
//#line 21 "../cfg/uav_local_planner.cfg"
      __max__.Posekp = 100.0;
//#line 21 "../cfg/uav_local_planner.cfg"
      __default__.Posekp = 8.0;
//#line 21 "../cfg/uav_local_planner.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("Posekp", "double", 0, "Roll/Pitch Proportional Gain for Position", "", &TutorialsConfig::Posekp)));
//#line 22 "../cfg/uav_local_planner.cfg"
      __min__.Posekd = 0.0;
//#line 22 "../cfg/uav_local_planner.cfg"
      __max__.Posekd = 100.0;
//#line 22 "../cfg/uav_local_planner.cfg"
      __default__.Posekd = 6.0;
//#line 22 "../cfg/uav_local_planner.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("Posekd", "double", 0, "Roll/Pitch Derivative Gain for Position", "", &TutorialsConfig::Posekd)));
//#line 23 "../cfg/uav_local_planner.cfg"
      __min__.Poseki = 0.0;
//#line 23 "../cfg/uav_local_planner.cfg"
      __max__.Poseki = 100.0;
//#line 23 "../cfg/uav_local_planner.cfg"
      __default__.Poseki = 0.0;
//#line 23 "../cfg/uav_local_planner.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("Poseki", "double", 0, "Roll/Pitch Integral  Gain for Position", "", &TutorialsConfig::Poseki)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<TutorialsConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<TutorialsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    TutorialsConfig __max__;
    TutorialsConfig __min__;
    TutorialsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const TutorialsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static TutorialsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &TutorialsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const TutorialsConfig &TutorialsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const TutorialsConfig &TutorialsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const TutorialsConfig &TutorialsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<TutorialsConfig::AbstractParamDescriptionConstPtr> &TutorialsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const TutorialsConfigStatics *TutorialsConfig::__get_statics__()
  {
    const static TutorialsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = TutorialsConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __TUTORIALSRECONFIGURATOR_H__
