(cl:defpackage uav_msgs-msg
  (:use )
  (:export
   "<CAMERA_MSG>"
   "CAMERA_MSG"
   "<CONTROLLERCOMMAND>"
   "CONTROLLERCOMMAND"
   "<FLIGHTMODESTATUS>"
   "FLIGHTMODESTATUS"
   "<FLIGHTMODEREQUEST>"
   "FLIGHTMODEREQUEST"
   "<MODE_MSG>"
   "MODE_MSG"
  ))

